spring:
server:
  port: 8080


  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=1
        - id: budget-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/budgets/**
          filters:
            - StripPrefix=1
        - id: scheduled-purchase-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/scheduled-purchases/**
          filters:
            - StripPrefix=1
        - id: analytics-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=1
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
