spring:
  server:
    port: 8080
  jpa:
    open-in-view: false
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: Y1JqNmM2cFNWcXY5ckYyNGFKcGJEa0I3V1FyU3ZLdDhON2tMWTNxWGpIcjlYN0Z2TjJaZ05NeDVwSDBmUDBaQg==
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=1
        - id: budget-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/budgets/**
          filters:
            - StripPrefix=1
        - id: analytics-service
          uri: http://localhost:8082  # Route to transaction service since analytics are part of it
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=1
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
  logging:
    level:
      root: DEBUG
      RequestLogger: DEBUG
      JwtAuthLogger: DEBUG
      org.springframework.cloud.gateway: DEBUG
  management:
    endpoints:
      web:
        exposure:
          include: health,info,gateway