server:
  port: 8083

spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:h2:mem:budgetdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    com.personalfinance.budget: DEBUG